language: ruby
rvm:
- 2.2.5
before_install:
  - gem install bundler -v '< 2.0'
  - gem update bundler
before_script:
- chmod +x ./script/cibuild.sh
script: "./script/cibuild.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
